SELECT NAME, DATE_YEAR, GENDER, US_STATE, NUM_BABIES FROM BABYNAMES
WHERE DATE_YEAR = 1991
AND US_STATE = 'MD'
AND GENDER = 'M'
ORDER BY NUM_BABIES DESC
FETCH FIRST 1 ROW ONLY;

SELECT NAME, DATE_YEAR, GENDER, NUM_BABIES FROM BABYNAMES
WHERE NAME = 'Christopher'
AND GENDER = 'M'
ORDER BY NUM_BABIES DESC
FETCH FIRST 1 ROW ONLY;

SELECT NAME, DATE_YEAR, GENDER, NUM_BABIES FROM BABYNAMES
WHERE NAME = 'Rosemary'
AND GENDER = 'F'
ORDER BY NUM_BABIES DESC
FETCH FIRST 1 ROW ONLY;

SELECT NAME, DATE_YEAR, GENDER, US_STATE, NUM_BABIES FROM BABYNAMES
WHERE NUM_BABIES > 500
AND DATE_YEAR = 2000
AND US_STATE = 'MD';

SELECT NAME, DATE_YEAR, GENDER, US_STATE, NUM_BABIES FROM BABYNAMES
WHERE NAME = 'Xavier'
AND GENDER = 'M'
AND DATE_YEAR = 2014
ORDER BY NUM_BABIES ASC
FETCH FIRST 1 ROW ONLY;

SELECT NAME, DATE_YEAR, GENDER, US_STATE, NUM_BABIES FROM BABYNAMES
WHERE NAME = 'Hannah'
AND GENDER = 'F'
AND DATE_YEAR = 1997
ORDER BY NUM_BABIES DESC
FETCH FIRST 1 ROW ONLY;

INSERT INTO BABYNAMES (ID, NAME, DATE_YEAR, GENDER, US_STATE, NUM_BABIES)
 VALUES (10000000, 'Joseph', 2016, 'M', 'PA', 476);

DELETE FROM BABYNAMES
WHERE ID = 10000000;








